spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lianhaotong0306
    url: jdbc:mysql://62.234.82.164:3306/huoji
    hikari:
      connection-timeout: 10000
      validation-timeout: 30000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)
server:
  port: 8080
  servlet:
    context-path: /api
